name: Daily data pull

on: 
  schedule: 
    - cron: "* 9 * * *"

jobs:
  get_data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
        MICROSOFT_TOKEN: ${{ secrets.MICROSOFT_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pipenv 
          
      - name: Setup Python dependencies 
        run: pip install pipenv
      
      - name: Get the data from api 
        run: |
          pipenv install --dev
          pipenv run python etl/get_and_clean_data.py
        

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

  